apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
spec:
  selector:
    matchLabels:
      app: runner
  replicas: 2
  template:
    metadata:
      labels:
        app: runner
    spec:
      serviceAccountName: gke-runner-sa
      automountServiceAccountToken: true
      containers:
        - name: runner
          image: gcr.io/dev1-cpt-sdlc-1-0817/runner:latest
          envFrom:
            - configMapRef:
                name: runner-k8s-config
            - secretRef:
                name: runner-k8s-secret
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/bash",
                    "-c",
                    'RUNNER_ALLOW_RUNASROOT=1 ./config.sh remove --token $(curl -sS --request POST --url "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/runners/remove-token" --header "authorization: Bearer ${GITHUB_TOKEN}"  --header "content-type: application/json" | jq -r .token)',
                  ]
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
