apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: runner-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runner-deployment
  minReplicas: 5
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
