apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deploy.yaml
- manifests/hpa.yaml
configMapGenerator:
- envs:
  - runner.env
  name: runner-k8s-config
images:
- name: gcr.io/dev1-cpt-sdlc-1-0817/runner:latest
  newName: gcr.io/gh-runners-e2e/runner
  newTag: latest
